version: '3.7'

services:
  backend:
    build: .
    command: yarn start
    volumes:
      - ./src/:/app/src/
    ports:
      - 3000:3000
    environment:
      - WEBHOOK_PROXY_URL=${WEBHOOK_PROXY_URL}
      - APP_ID=${APP_ID}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
